/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelSlaveCommProblem.java
 *
 * Created on Apr 30, 2012, 11:02:18 AM
 */
package view.fdl;

import consolesimulator.ProfibusSimulator;
import consolesimulator.ProfibusSimulatorSingleton;

/**
 *
 * @author Renato Veiga
 */
public class jPanelSlaveCommProblem extends javax.swing.JPanel {

    protected SlaveObj slv1 = new SlaveObj();
    ProfibusSimulator Sim = ProfibusSimulatorSingleton.getInstance();
    
    /** Creates new form jPanelSlaveCommProblem */
    public jPanelSlaveCommProblem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jSliderVoltage = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jVoltageLabel = new javax.swing.JLabel();
        jCheckBoxReadableSignal = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProblemType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(profibusnetworksimulator.ProfibusNetworkSimulatorAppNew.class).getContext().getResourceMap(jPanelSlaveCommProblem.class);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jSliderVoltage.setMaximum(10);
        jSliderVoltage.setValue(7);
        jSliderVoltage.setName("jSliderVoltage"); // NOI18N
        jSliderVoltage.setValueIsAdjusting(true);
        jSliderVoltage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVoltageStateChanged(evt);
            }
        });

        jLabel2.setName("jLabel2"); // NOI18N

        jVoltageLabel.setText(resourceMap.getString("jVoltageLabel.text")); // NOI18N
        jVoltageLabel.setName("jVoltageLabel"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSliderVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jVoltageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVoltageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = -35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 11, 0);
        add(jPanel4, gridBagConstraints);

        jCheckBoxReadableSignal.setSelected(true);
        jCheckBoxReadableSignal.setText(resourceMap.getString("jCheckBoxReadableSignal.text")); // NOI18N
        jCheckBoxReadableSignal.setName("jCheckBoxReadableSignal"); // NOI18N
        jCheckBoxReadableSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReadableSignalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jCheckBoxReadableSignal, gridBagConstraints);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        add(jLabel1, gridBagConstraints);

        jComboBoxProblemType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Problem", "Terminator Missing", "Terminator Excess", "A-B Short Circuit", "Cable Break", "Cable Long", "Terminator Power Supply failure (*)", "Spur-lines (*)", "Corrupted Signal" }));
        jComboBoxProblemType.setName("jComboBoxProblemType"); // NOI18N
        jComboBoxProblemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProblemTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        add(jComboBoxProblemType, gridBagConstraints);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 10);
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void setSlaveObject(SlaveObj slaveObj){
    //addressLabel.setText( Integer.toString(slaveObj.getAddress()) );
    //slv1.setAddress( slaveObj.getAddress() );

    if( slv1.getAddress() >= 0 )
    {
        //Combo Update
        jComboBoxProblemType.setSelectedIndex( Sim.getSlavePhyProblem( slv1.getAddress() ) );

        //Voltage Bar Update
        jSliderVoltage.setValue( Sim.getSlaveVoltage( slv1.getAddress() ) );

        //Readable Signal Update
        jCheckBoxReadableSignal.setSelected( Sim.getReadableSignal( slv1.getAddress() ) );
    }

    revalidate();
}

    
    
private void jComboBoxProblemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProblemTypeActionPerformed
        Sim.setSlavePhyProblem( slv1.getAddress(), jComboBoxProblemType.getSelectedIndex() );
}//GEN-LAST:event_jComboBoxProblemTypeActionPerformed

private void jCheckBoxReadableSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReadableSignalActionPerformed
        Sim.setReadable( slv1.getAddress(), jCheckBoxReadableSignal.isSelected() );
}//GEN-LAST:event_jCheckBoxReadableSignalActionPerformed

private void jSliderVoltageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVoltageStateChanged
        int newvalue = jSliderVoltage.getValue();
        String st = new String();

        if( newvalue < 4 ) {
            st = "(Low)";
        }
        else if (newvalue >= 4 && newvalue <= 7) {
            st = "(Normal)";
        }
        else if (newvalue > 7) {
            st = "(Over)";
        }
       
        jVoltageLabel.setText( Integer.toString( newvalue ) + "V " + st );
        
        Sim.setSlaveVoltage( slv1.getAddress(), newvalue );
}//GEN-LAST:event_jSliderVoltageStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxReadableSignal;
    private javax.swing.JComboBox jComboBoxProblemType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSliderVoltage;
    private javax.swing.JLabel jVoltageLabel;
    // End of variables declaration//GEN-END:variables
}
