/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SlavePanel.java
 *
 * Created on 12/01/2011, 11:29:06
 */

package view.fdl;

import SlaveDialog.DiagnosticDialog;
import consolesimulator.ProfibusSimulator;
import consolesimulator.ProfibusSimulatorSingleton;
import javax.swing.JFrame;

/**
 *
 * @author emossin
 */
public class SlavePanel extends javax.swing.JPanel {
    
    protected SlaveObj slv1 = new SlaveObj();
    ProfibusSimulator Sim = null; // = ProfibusSimulatorSingleton.getInstance();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton jButtonChangeConfiguration;
    private javax.swing.JButton jButtonChangeDiag;
    private javax.swing.JButton jButtonGoOnline;
    // End of variables declaration//GEN-END:variables
    private final int slaveAddr;

    
    /** Creates new form SlavePanel */
    public SlavePanel(int slaveAddrPrm) {
        initComponents();
        slaveAddr = slaveAddrPrm;
        
        addressLabel.setText( "Address: " + Integer.toString( slaveAddr ) );
        
        UpdateButton();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonChangeDiag = new javax.swing.JButton();
        jButtonChangeConfiguration = new javax.swing.JButton();
        jButtonGoOnline = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(profibusnetworksimulator.ProfibusNetworkSimulatorAppNew.class).getContext().getResourceMap(SlavePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setForeground(getBackground());
        setName("Form"); // NOI18N

        jButtonChangeDiag.setText(resourceMap.getString("jButtonChangeDiag.text")); // NOI18N
        jButtonChangeDiag.setName("jButtonChangeDiag"); // NOI18N
        jButtonChangeDiag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeDiagActionPerformed(evt);
            }
        });

        jButtonChangeConfiguration.setText(resourceMap.getString("jButtonChangeConfiguration.text")); // NOI18N
        jButtonChangeConfiguration.setName("jButtonChangeConfiguration"); // NOI18N
        jButtonChangeConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeConfigurationActionPerformed(evt);
            }
        });

        jButtonGoOnline.setText(resourceMap.getString("jButtonGoOnline.text")); // NOI18N
        jButtonGoOnline.setName("jButtonGoOnline"); // NOI18N
        jButtonGoOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoOnlineActionPerformed(evt);
            }
        });

        addressLabel.setFont(resourceMap.getFont("addressLabel.font")); // NOI18N
        addressLabel.setText(resourceMap.getString("addressLabel.text")); // NOI18N
        addressLabel.setName("addressLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(addressLabel))
                    .addComponent(jButtonChangeDiag)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonChangeConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonGoOnline)))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addressLabel)
                .addGap(6, 6, 6)
                .addComponent(jButtonChangeDiag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonChangeConfiguration)
                    .addComponent(jButtonGoOnline))
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonChangeDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDiagActionPerformed
        JFrame jDiag = new DiagnosticDialog( slaveAddr );
        jDiag.setVisible(true);
    }//GEN-LAST:event_jButtonChangeDiagActionPerformed

private void jButtonGoOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoOnlineActionPerformed
        Sim = ProfibusSimulatorSingleton.getInstance();
        
        if( Sim.isSlaveOnline( slaveAddr ) == true )
            Sim.SetSlaveOnline(slaveAddr, false);
        else
            Sim.SetSlaveOnline(slaveAddr, true);
        
        UpdateButton();
        
        revalidate();
}//GEN-LAST:event_jButtonGoOnlineActionPerformed

private void jButtonChangeConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeConfigurationActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButtonChangeConfigurationActionPerformed
        

private void UpdateButton() {
    if( Sim != null && slaveAddr >= 0 )
    {
        if( Sim.isSlaveOnline( slaveAddr ) == true )
            jButtonGoOnline.setText("GO OFFLINE");
        else
            jButtonGoOnline.setText("GO ONLINE");
        }
    }
}
