/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiagnosticDialog.java
 *
 * Created on May 3, 2011, 11:44:38 AM
 */

package SlaveDialog;

/**
 *
 * @author Veiga
 */
public class DiagnosticDialog extends javax.swing.JFrame {
    
    DiagAndCfgStationInterface ditf;

    /** Creates new form DiagnosticDialog */
    public DiagnosticDialog(int addr) {
        initComponents();
        ditf = new DiagAndCfgStationInterface(addr);
        fillCheckBoxes( ditf.getSlaveDiagBits() );
        //jTextFieldForceIdent.setText( ditf.g );
        jLabelAddress.setText("Address: "+ Integer.toString(addr));
        jLabelMaster.setText("Master Address: "+ Integer.toString(ditf.getSlavesMaster()));
        jLabelIdent.setText("Ident Number: "+ ditf.getSlaveIdentNumber());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jLabelMaster = new javax.swing.JLabel();
        jLabelIdent = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(profibusnetworksimulator.ProfibusNetworkSimulatorAppNew.class).getContext().getResourceMap(DiagnosticDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N

        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jCheckBox3.setText(resourceMap.getString("jCheckBox3.text")); // NOI18N
        jCheckBox3.setName("jCheckBox3"); // NOI18N

        jCheckBox4.setText(resourceMap.getString("jCheckBox4.text")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        jCheckBox5.setText(resourceMap.getString("jCheckBox5.text")); // NOI18N
        jCheckBox5.setName("jCheckBox5"); // NOI18N

        jCheckBox6.setText(resourceMap.getString("jCheckBox6.text")); // NOI18N
        jCheckBox6.setName("jCheckBox6"); // NOI18N

        jCheckBox7.setText(resourceMap.getString("jCheckBox7.text")); // NOI18N
        jCheckBox7.setName("jCheckBox7"); // NOI18N

        jCheckBox8.setText(resourceMap.getString("jCheckBox8.text")); // NOI18N
        jCheckBox8.setName("jCheckBox8"); // NOI18N

        jCheckBox9.setText(resourceMap.getString("jCheckBox9.text")); // NOI18N
        jCheckBox9.setName("jCheckBox9"); // NOI18N

        jCheckBox10.setText(resourceMap.getString("jCheckBox10.text")); // NOI18N
        jCheckBox10.setName("jCheckBox10"); // NOI18N

        jCheckBox11.setText(resourceMap.getString("jCheckBox11.text")); // NOI18N
        jCheckBox11.setName("jCheckBox11"); // NOI18N

        jCheckBox12.setText(resourceMap.getString("jCheckBox12.text")); // NOI18N
        jCheckBox12.setName("jCheckBox12"); // NOI18N

        jCheckBox13.setText(resourceMap.getString("jCheckBox13.text")); // NOI18N
        jCheckBox13.setName("jCheckBox13"); // NOI18N

        jCheckBox14.setText(resourceMap.getString("jCheckBox14.text")); // NOI18N
        jCheckBox14.setName("jCheckBox14"); // NOI18N

        jCheckBox15.setText(resourceMap.getString("jCheckBox15.text")); // NOI18N
        jCheckBox15.setName("jCheckBox15"); // NOI18N

        jCheckBox16.setText(resourceMap.getString("jCheckBox16.text")); // NOI18N
        jCheckBox16.setName("jCheckBox16"); // NOI18N

        jLabelMaster.setText(resourceMap.getString("jLabelMaster.text")); // NOI18N
        jLabelMaster.setName("jLabelMaster"); // NOI18N

        jLabelIdent.setText(resourceMap.getString("jLabelIdent.text")); // NOI18N
        jLabelIdent.setName("jLabelIdent"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelAddress.setFont(resourceMap.getFont("jLabelAddress.font")); // NOI18N
        jLabelAddress.setText(resourceMap.getString("jLabelAddress.text")); // NOI18N
        jLabelAddress.setName("jLabelAddress"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox3)
                                        .addComponent(jCheckBox4)
                                        .addComponent(jCheckBox5)
                                        .addComponent(jCheckBox6)
                                        .addComponent(jCheckBox8)
                                        .addComponent(jCheckBox7))
                                    .addGap(48, 48, 48))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelIdent)
                                        .addComponent(jLabelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addContainerGap())
                                .addComponent(jCheckBox13)
                                .addComponent(jCheckBox14)
                                .addComponent(jCheckBox15)
                                .addComponent(jCheckBox16)
                                .addComponent(jCheckBox9)
                                .addComponent(jCheckBox10)
                                .addComponent(jCheckBox11)
                                .addComponent(jCheckBox12))))
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMaster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIdent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ditf.modifySlaveDiagAndCfg( getCheckBoxDiagBits() );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean[] getCheckBoxValues( )
    {
        boolean[] bret = new boolean[16];
        
        if( jCheckBox1.isSelected() == true ) bret[0] = true;
        else bret[0] = false;
        
        if( jCheckBox2.isSelected() == true ) bret[1] = true;
        else bret[1] = false;

        if( jCheckBox3.isSelected() == true ) bret[2] = true;
        else bret[2] = false;

        if( jCheckBox4.isSelected() == true ) bret[3] = true;
        else bret[3] = false;

        if( jCheckBox5.isSelected() == true ) bret[4] = true;
        else bret[4] = false;

        if( jCheckBox6.isSelected() == true ) bret[5] = true;
        else bret[5] = false;

        if( jCheckBox7.isSelected() == true ) bret[6] = true;
        else bret[6] = false;
        
        if( jCheckBox8.isSelected() == true ) bret[7] = true;
        else bret[7] = false;

        if( jCheckBox9.isSelected() == true ) bret[8] = true;
        else bret[8] = false;
        
        if( jCheckBox10.isSelected() == true ) bret[9] = true;
        else bret[9] = false;

        if( jCheckBox11.isSelected() == true ) bret[10] = true;
        else bret[10] = false;

        if( jCheckBox12.isSelected() == true ) bret[11] = true;
        else bret[11] = false;

        if( jCheckBox13.isSelected() == true ) bret[12] = true;
        else bret[12] = false;

        if( jCheckBox14.isSelected() == true ) bret[13] = true;
        else bret[13] = false;

        if( jCheckBox15.isSelected() == true ) bret[14] = true;
        else bret[14] = false;
        
        if( jCheckBox16.isSelected() == true ) bret[15] = true;
        else bret[15] = false;
        
        return bret;
    }
    
    public byte[] getCheckBoxDiagBits( )
    {
        byte b[] = new byte[2];
        
        b[0] |= (jCheckBox1.isSelected() == true) ? 0x01 : 0x00;
        b[0] |= (jCheckBox2.isSelected() == true) ? 0x02 : 0x00;
        b[0] |= (jCheckBox3.isSelected() == true) ? 0x04 : 0x00;
        b[0] |= (jCheckBox4.isSelected() == true) ? 0x08 : 0x00;
        b[0] |= (jCheckBox5.isSelected() == true) ? 0x10 : 0x00;
        b[0] |= (jCheckBox6.isSelected() == true) ? 0x20 : 0x00;
        b[0] |= (jCheckBox7.isSelected() == true) ? 0x40 : 0x00;
        b[0] |= (jCheckBox8.isSelected() == true) ? 0x80 : 0x00;

        //Octet 2
        b[1] |= (jCheckBox9.isSelected() == true) ? 0x01 : 0x00;
        b[1] |= (jCheckBox10.isSelected() == true)? 0x02 : 0x00;
        b[1] |= (jCheckBox11.isSelected() == true)? 0x04 : 0x00;
        b[1] |= (jCheckBox12.isSelected() == true)? 0x08 : 0x00;
        b[1] |= (jCheckBox13.isSelected() == true)? 0x10 : 0x00;
        b[1] |= (jCheckBox14.isSelected() == true)? 0x20 : 0x00;
        b[1] |= (jCheckBox15.isSelected() == true)? 0x80 : 0x00;
        
        return b;
    }
    
    public void fillCheckBoxes(byte[] b )
    {
        boolean v[] = new boolean[16];
        
        if( b.length >= 2 )
        {
            //Octet 1
            v[0] = ((b[0] & 0x01) != 0) ? true : false;
            v[1] = ((b[0] & 0x02) != 0) ? true : false;
            v[2] = ((b[0] & 0x04) != 0) ? true : false;
            v[3] = ((b[0] & 0x08) != 0) ? true : false;
            v[4] = ((b[0] & 0x10) != 0) ? true : false;
            v[5] = ((b[0] & 0x20) != 0) ? true : false;
            v[6] = ((b[0] & 0x40) != 0) ? true : false;
            v[7] = ((b[0] & 0x80) != 0) ? true : false;

            //Octet 2
            v[8] = ((b[1] & 0x01) != 0) ? true : false;
            v[9] = ((b[1] & 0x02) != 0) ? true : false;
            v[10]= ((b[1] & 0x04) != 0) ? true : false;
            v[11]= ((b[1] & 0x08) != 0) ? true : false;
            v[12]= ((b[1] & 0x10) != 0) ? true : false;
            v[13]= ((b[1] & 0x20) != 0) ? true : false;
            v[14]= ((b[1] & 0x40) != 0) ? true : false;
            v[15]= ((b[1] & 0x80) != 0) ? true : false;

            fillDiagCheckBoxes(v);
        }
    }
    
    public void fillDiagCheckBoxes(boolean[] b )
    {
        jCheckBox1.setSelected(b[0]);
        jCheckBox2.setSelected(b[1]);
        jCheckBox3.setSelected(b[2]);
        jCheckBox4.setSelected(b[3]);
        jCheckBox5.setSelected(b[4]);
        jCheckBox6.setSelected(b[5]);
        jCheckBox7.setSelected(b[6]);
        jCheckBox8.setSelected(b[7]);
        jCheckBox9.setSelected(b[8]);
        jCheckBox10.setSelected(b[9]);
        jCheckBox11.setSelected(b[10]);
        jCheckBox12.setSelected(b[11]);
        jCheckBox13.setSelected(b[12]);
        jCheckBox14.setSelected(b[13]);
        jCheckBox15.setSelected(b[14]);
        jCheckBox16.setSelected(b[15]);
    }
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelIdent;
    private javax.swing.JLabel jLabelMaster;
    // End of variables declaration//GEN-END:variables

}
