/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SlavePanel.java
 *
 * Created on 19/05/2010, 16:16:16
 */
package view;

import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SingleSelectionModel;

/**
 *
 * @author eduardo_mossin
 */
public abstract class SlavePanel extends javax.swing.JPanel {

    private boolean isOn = false;
    private boolean hasError = false;
    private JPopupMenu SlaveMenu;
    private JMenuItem Item, Item2;


    /** Creates new form SlavePanel */
    public SlavePanel() {
        initComponents();
    }
    
    public void setOFF() {
        setIsOn(false);
    }

    public void setON() {
        setIsOn(true);
    }

    public void setWithError() {
        setHasError(true);
    }

    public void setWithoutError() {
        setHasError(false);
    }

  public void setIcon() {
        URL url = null;
        if (!isHasError()) {
            if (isIsOn()) {
                url = ClassLoader.getSystemResource("view/resources/deviceON.GIF");
            } else {
                url = ClassLoader.getSystemResource("view/resources/deviceOFF.GIF");
            }
        } else {
            url = ClassLoader.getSystemResource("view/resources/deviceERROR.GIF");
        }


        ImageIcon icon = new ImageIcon(url);
        getjLabel2().setIcon(icon);
    }

    public abstract void  changeStatus();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(profibusnetworksimulator.ProfibusNetworkSimulatorAppNew.class).getContext().getResourceMap(SlavePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setForeground(resourceMap.getColor("Form.foreground")); // NOI18N
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        addressLabel.setFont(resourceMap.getFont("addressLabel.font")); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressLabel.setText(resourceMap.getString("addressLabel.text")); // NOI18N
        addressLabel.setName("addressLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                    .addComponent(addressLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        changeStatus();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if( evt.getButton() == MouseEvent.BUTTON3)
        {
            SlaveMenu.setLocation(getX(), getY());
            SlaveMenu.setVisible(true);
        }
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the isOn
     */
    public boolean isIsOn() {
        return isOn;
    }

    /**
     * @param isOn the isOn to set
     */
    public void setIsOn(boolean isOn) {
        this.isOn = isOn;
    }

    /**
     * @return the addressLabel
     */
    public javax.swing.JLabel getAddressLabel() {
        return addressLabel;
    }

    /**
     * @param addressLabel the addressLabel to set
     */
    public void setAddressLabel(javax.swing.JLabel addressLabel) {
        this.addressLabel = addressLabel;
    }

    public void setAddressLabel(int address) {
        this.getAddressLabel().setText(Integer.toString(address));
    }

    /**
     * @return the hasError
     */
    public boolean isHasError() {
        return hasError;
    }

    /**
     * @param hasError the hasError to set
     */
    public void setHasError(boolean hasError) {
        this.hasError = hasError;
    }
}
